// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLr-nu9yKnAfd6_BB09_nF90LkLkIEHE',
    appId: '1:871359395886:web:f36e6e91d8ec35d1a247bf',
    messagingSenderId: '871359395886',
    projectId: 'coffeecup-dcf6c',
    authDomain: 'coffeecup-dcf6c.firebaseapp.com',
    storageBucket: 'coffeecup-dcf6c.appspot.com',
    measurementId: 'G-HJ926XPFWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM_yFVAkgPxT_wGIVbd8V0aVHzQDI4aCk',
    appId: '1:871359395886:android:cfdcaa75981a8baba247bf',
    messagingSenderId: '871359395886',
    projectId: 'coffeecup-dcf6c',
    storageBucket: 'coffeecup-dcf6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKbP9-RPcYIlmWWooMLcfEGKSwZYmLZwc',
    appId: '1:871359395886:ios:9f95ed3a2061c8cea247bf',
    messagingSenderId: '871359395886',
    projectId: 'coffeecup-dcf6c',
    storageBucket: 'coffeecup-dcf6c.appspot.com',
    iosClientId: '871359395886-sjkm5046f1r3b5ks073r4g217er810qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cofffecup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKbP9-RPcYIlmWWooMLcfEGKSwZYmLZwc',
    appId: '1:871359395886:ios:65cd728792886f1ca247bf',
    messagingSenderId: '871359395886',
    projectId: 'coffeecup-dcf6c',
    storageBucket: 'coffeecup-dcf6c.appspot.com',
    iosClientId: '871359395886-6hjr75u2h5idviu639gl0o332jf73qtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cofffecup.RunnerTests',
  );
}
